name: purpur
services:
  purpur:
    container_name: purpur
    build: .
    image: purpur_image
    volumes:
      - purpur_volume:/opt/minecraft
      - ./setup:/opt/setup
    ports:
      - 25565:25565
    command: start
    stop_signal: SIGINT
    stop_grace_period: 30s
    environment:
      TZ: Asia/Tokyo
      JAVA_MEMORY_MAX: 8G
      JAVA_MEMORY_MIN: 8G
volumes:
  purpur_volume:
