name: purpur
services:
  purpur:
    container_name: purpur
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=${VERSION}
    env_file:
      - .env
    image: purpur_image
    volumes:
      - purpur_volume:/opt/minecraft
      - ./setup:/opt/setup
      - ./backup:/opt/backup
    ports:
      - 25565:25565
    command: start
    stop_signal: SIGINT
    stop_grace_period: 30s
  log_watcher:
    container_name: log_watcher
    build:
      context: .
      dockerfile: Dockerfile_logwatcher
    env_file:
      - .env
    volumes:
      - purpur_volume:/opt/minecraft
#    restart: always
volumes:
  purpur_volume:
