name: purpur
services:
  purpur:
    container_name: purpur
    build: .
    env_file:
      - .env
    image: purpur_image
    volumes:
      - purpur_volume:/opt/minecraft
      - ./setup:/opt/setup
      - ./backup:/opt/backup
    ports:
      - 25565:25565
    command: start
    stop_signal: SIGINT
    stop_grace_period: 30s
volumes:
  purpur_volume:
